DELETE http://localhost:8080/api/user/US00000003
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyZW9saW5vQGdtYWlsLmNvbSIsImxvZ2luX2lkIjoicmVvbGlub0BnbWFpbC5jb20iLCJ1c2VyX3B3IjoiMGZmZTFhYmQxYTA4MjE1MzUzYzIzM2Q2ZTAwOTYxM2U5NWVlYzQyNTM4MzJhNzYxYWYyOGZmMzdhYzVhMTUwYyIsInVzZXJfaWQiOiJVUzAwMDAwMDAzIiwidXNlcl9ubSI6InJlb2xpbm8iLCJleHAiOjE2NzQxMjg3MzYsImlhdCI6MTY3NDExNDMzNn0.jcQ-DRJk1ckB0UBXyvN1a9hxt-2A4zJ0nsP3-XWrI9Q
