PUT http://localhost:8080/api/board
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyZW9saW5vQGdtYWlsLmNvbSIsImxvZ2luX2lkIjoicmVvbGlub0BnbWFpbC5jb20iLCJ1c2VyX3B3IjoiMGZmZTFhYmQxYTA4MjE1MzUzYzIzM2Q2ZTAwOTYxM2U5NWVlYzQyNTM4MzJhNzYxYWYyOGZmMzdhYzVhMTUwYyIsInVzZXJfaWQiOiJVUzAwMDAwMDA3IiwidXNlcl9ubSI6InJlb2xpbm8iLCJleHAiOjE3MDY5NDA0NDEsImlhdCI6MTY3NTgzNjQ0MX0.AucT25OMKjHkon7jw-0wLywW5se9v71Mmbn7yz27IEg

{
  "board_title": "테스트 QNA게시판",
  "board_type":"QNA",
  "memo": "테스트 QNA게시판입니다",
  "auth_id_arr" : ["AT00000002"]
}



