POST http://localhost:8080/api/codeGrp
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyZW9saW5vQGdtYWlsLmNvbSIsImxvZ2luX2lkIjoicmVvbGlub0BnbWFpbC5jb20iLCJ1c2VyX3B3IjoiMGZmZTFhYmQxYTA4MjE1MzUzYzIzM2Q2ZTAwOTYxM2U5NWVlYzQyNTM4MzJhNzYxYWYyOGZmMzdhYzVhMTUwYyIsInVzZXJfaWQiOiJVUzAwMDAwMDA3IiwidXNlcl9ubSI6InJlb2xpbm8iLCJleHAiOjE2NzU2NjE2NDYsImlhdCI6MTY3NTY0NzI0Nn0.1EvI8uMY7PcEgDbLomoEl992DFjqcYFP8X5Eqiqw2pY

{
  "use_yn": "Y",
  "search_str":"페이징"
}

